### PR TITLE
Revert "Scrutinizer Auto-Fixes"

### LINKED ISSUE #582: Scrutinizer make mess everywhere
PHP code broken here :
extensions/ki_adminpanel/init.php on line 131
extensions/ki_adminpanel/processor.php on line 113
extensions/ki_adminpanel/processor.php on line 115

### PR DESCRIPTION
**Pull request by simonschaufi**
Reverts kimai/kimai#577
Resolves #582

### CODE REVIEW

**Comment by kevinpapst** [comment]
This is an automated revert of the one commit, correct? Lets merge it, before any other PR

**Comment by simonschaufi** [comment]
yes. generated by github.

**Comment by simonschaufi** [comment]
all the other code changes were fine, or?

**Comment by kevinpapst** [comment]
I didn't try them yet... I thought you did. Okay, updated my local environment, I will use it for development as see how it goes

**Comment by kevinpapst** [comment]
There is still a bug: https://github.com/kimai/kimai/blob/master/includes/func.php#L136

Comes from that commit:
https://github.com/kimai/kimai/commit/02e8161174fda8d980f9387d051c96e41b3da130#diff-226aa98ef3dc8a475a8418c3678e0b25R136

**Comment by kevinpapst** [comment]
Probably we can fix that one manually in includes/func.php and keep the rest? 

```
            if (!$database->global_role_allows($kga['user']['globalRoleID'], 'core-group-otherGroup-view')) {
                  $groups = array_filter(
                      $groups,
                      function($group) {
                          global $kga;
                          return array_search($group['groupID'], $kga['user']['groups']) !== false;
                      }
                  );
            }
```

I am not sure, better to revert nevertheless...

**Pull request merged**
