### PR TITLE
Delete log messsage configurable with language module

### PR DESCRIPTION
**Pull request by claudegel**
A small one to make the delete log message to be configurable in the language module.
The en and fr files already updated for that purpose (see end of files)

### CODE REVIEW

**Comment by kevinpapst** [comment]
We need the translation in every language file. If you can't translate it, just add the key there.

And please: no more whitespace changes in the future. I do agree that re-formatting should be done ... but only if the team discussed first in which way - and then we should do it with one huge commit (or file-by-file) - but without logic changes in between.

**Comment by ServiusHack** [comment]
Since quite some time it's not necessary to have the translation key in every translation file. First the English translation is loaded (in translations.class.php). Then this is merged with the language specified in autoconf.php (in basics.php). Finally this is merged with the language specified in the admin tab and the user preference (in Mysql.php). If one translation file doesn't contain a translation key then the English translation (or any other that overwrote it) is used.

**Comment by kevinpapst** [comment]
True, but it makes it harder for people to translate everything to their language :)

**Comment by claudegel** [comment]
Ok I'll add in each language. With google translation it's possible to get something basic. I will also update the fr.php as I found that many key were missing.

**Comment by claudegel** [comment]
how can I delete a branch on github once it have been merged like my bugfix branch. I can delete it locally but can<t find out how to do it on github

**Comment by kevinpapst** [comment]
The command is "git push origin --delete yourbranchname".

**Pull request merged**
