### PR TITLE
=closes #383

### PR DESCRIPTION
**Pull request by paulsteffen**
- permission check in function "timesheetAccessAllowed" fixed to work with editLimit setting
- fixed one typo in german translation

### CODE REVIEW

**Comment by kevinpapst** [comment]
Could you please describe the problem, so I can reproduce it?

**Comment by kevinpapst** [comment]
Ah, okay, I found the problem. Let me check your fix and then I will merge it!

**Comment by paulsteffen** [comment]
If editLimit is set in the configuration it is impossible to start a new recording based on another one.
(Admin Panel -> Advanced -> check "No entries can be added or edited with en more than" and insert any value)
If you click on the "Record this recording again" button in front of any timesheet entry the recording does not start 

/extensions/ki_timesheets/processor.php line 96 ->  $timeSheetEntry['end'] = 0;
so the function "timesheetAccessAllowed" will always return false if  $kga['conf']['editLimit'] != '-'

**Comment by kevinpapst** [comment]
:) Very good, thanks for finding and fixing!

**Pull request merged**
