### PR TITLE
Sort invoice line items alphabetically by activity

### LINKED ISSUE #187: Order tasks alphabetically on invoice
There is a certain order in my project tasks, for instance:

01 Design
02 Build
03 Test
04 Deliver

I would like to have that exact order on my invoice (with sum hours), but at the moment the order is different. My request for change is to order the project tasks on the invoice alphabetically.
  
--
Hi vissersj,

I see that this can be of use. Please go to vissersj https://github.com/kimai/kimai/issues and file a feature request there.

Best Regards,
Severin

### PR DESCRIPTION
**Pull request by EverPresent**
I added a simple call to usort to fix #187

### CODE REVIEW

**Comment by kevinpapst** [comment]
I am not sure about this one here. How are they ordered currently?
We would change all invoices for all users with this commit.

Without reviewing the current code, I would say that this should be configurable through the UI for every invoice.

**Comment by EverPresent** [comment]
I don’t believe there was a sort on this at all so I _think_ it was just displaying the list in whatever order the DB returned them.  But it’s been some time since I looked.

**Comment by EverPresent** [comment]
Yeah.  Looking back I think I have to agree with you, Kevin.  The invoice print code has changed _considerably_ since this patch, it should also probably have a UI setting.  This should be re-coded.  I'll see if I have time in the next few weeks to update my installation and do it.

**Comment by kevinpapst** [comment]
Ok, then I will close this pull request. Please send in a new one :)

**Pull request closed without merging**
