### PR TITLE
add default_location to preferences to be filled in new timesheet

### PR DESCRIPTION
**Pull request by claudegel**
This one replace my previous pull request for default location

### CODE REVIEW

**Comment by simonschaufi** [comment]
can you please replace DefLocation with defaultLocation and DefaultLocation with defaultLocation? variables should be lowerCamelCase

**Comment by claudegel** [comment]
Ok I'll do it tonight

Claude Gelinas agr.
Phyto Ressources Inc.

**Comment by simonschaufi** [comment]
closes #434

**Comment by claudegel** [comment]
done thank you

**Pull request merged**
