### PR TITLE
Saml auth2

### LINKED ISSUE #961: SAML support
Hi

I am looking at implementing SAML support for my use in our instalation.  I am now looking at how the php-saml library should be installed.

It looks like I can use composer but that would install its own vendor directory instead of the libraries directory that the other libraries use.  

Should I simply download the php-saml library and add it to the libraries directory or does it make sens to go the composer route?

Tim

### PR DESCRIPTION
**Pull request by timlegge**
FIXES #961 #960 

Changes proposed in this pull request:
- 
Addition of SAML Authenticator.  Allows you to authenticate to Kimai via SAML.  Tested against Google's GSuite SAML Identity Provider

Reason for this pull request:
- 
More eyes on the code.  Anyone wanting to test contact me and I can provide a temporary account on my GSuite domain.

Documentation:
- 
https://github.com/kimai/documentation/pull/10

### CODE REVIEW

**Comment by simonschaufi** [comment]
Thank you Tim!
Since I want to require composer sooner or later anyway for git installer, it will be better to not add so many library files into the core of kimai. For the releases it will be included but that is just a zip. If we add it now, it will always be in the history, even if we will delete them later on.
If everything is working properly now, I will merge it as soon as the library code is removed.
You can just delete everything and then amend the commit and force push.

**Comment by timlegge** [comment]
I will work on it.  Just on vacation at the moment so it might be a week or two

**Comment by philipp-doblhofer** [comment]
@timlegge Can you predict when it's ready to merge, because it would be a nice feature for kimai ;)

**Comment by timlegge** [comment]
the changes are trivial.  I am rebasing and testing.  some time this week or weeken

**Comment by simonschaufi** [comment]
@timlegge Hi Tim, could you please now remove all the composer dependency files and look for the conflicting files? I would be glad if I can merge this finally.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).

**Pull request closed without merging**
