### PR TITLE
Implement updateActiveRecording function in the api, and add description to the getActiveRecording response

### PR DESCRIPTION
**Pull request by JonnyHonda**
## updateActiveRecording
This PR implements a new function in Kimai_Remote_API, the purpose of which is to allow an active timer to be updated.

This function replicates the frontend Use Case where a timer has been started and the user wishes to change the start time, project, activity and description without having to stop it first. 

Should an end time be specified it will be applied in the update and the timer will be ended as per Kimai's existing functionality.

Json Curl Examples:
Update the current active recording's projectID, taskID and Description.
`
curl --data '{"jsonrpc": "2.0","method": "updateActiveRecording","params": ["49945438e826988f2e31d8972", {"projectID": 3,"taskID": 2,"description": "Switch Project example"}],"id": "1"}' http://192.168.1.90/core/json.php
`

Updates the start time, end time and sets a description
`
curl --data '{"jsonrpc": "2.0","method": "updateActiveRecording","params": ["49945438e826988f2e31d8972", {"description": "I finished this task early","start": "2018-02-28 11:00:00","end":"2018-02-28 16:00:00"}],"id": "1"}' http://192.168.1.90/core/json.php
{"result":{"success":true,"items":[],"total":0},"id":"1","jsonrpc":"2.0"}
`

This function is not intended to be a full update timesheet function only a simple update 

Note, I've also added the description field to the getActiveRecording response.

Full example Json object expected by the call
```
{
	"jsonrpc": "2.0",
	"method": "updateActiveRecording",
	"params": ["49945438e826988f2e31d8972", {
		"timeEntryID": 53,
		"projectId": 1,
		"taskId": 1,
		"description": "Some funky new functionality",
		"start": "2018-02-28 07:00:00",
		"end": "2018-02-28 17:00:00"
	}],
	"id": "1"
}
```

### CODE REVIEW

**Comment by simonschaufi** [comment]
Please fix the code style with this patch: https://styleci.io/analyses/8bBvJw

**Comment by kevinpapst** [comment]
Thanks for your contribution @JonnyHonda 👍 
Now we have two PRs that implement a updateEntry method, see the quite old PR #829 also.
@JonnyHonda would you mind merging yours and the linked one into a new PR?

**Comment by JonnyHonda** [comment]
Hey guys, all this patching and merging is quite new to me, I did look at the old PR and disregarded it as rejected since it was over 2 years old.

**Comment by simonschaufi** [comment]
Let me merge this one as i find your's a lot cleaner than the other one. We can still add the other changes later on.

**Review by simonschaufi — APPROVED** [review]

**Pull request merged**
