### PR TITLE
	Use glob to find languages

### PR DESCRIPTION
**Pull request by simonschaufi**
If we decide to drop the PR, we should instead find a better solution for files iteration. My suggestion is to use [glob](http://php.net/glob).

### CODE REVIEW

**Comment by kevinpapst** [comment]
The new class seems to be perfect testable ...
And yes, using glob seems more elegant ;-) but both version are fine

**Comment by simonschaufi** [comment]
ok then let's not introduce more code that's not needed. I copied the class anyway from another framework ;)

**Comment by kevinpapst** [comment]
Close then?

**Comment by kevinpapst** [comment]
Ups, wrong button - you can reopen if desired

**Comment by simonschaufi** [comment]
undoing a pr is only possible with a revert commit.

**Comment by kevinpapst** [comment]
Why a milestone if nothing happened?

**Comment by simonschaufi** [comment]
since it's merged into master, it will be in the 1.0 release.

**Comment by kevinpapst** [comment]
Nope, it wasn't merged.

**Comment by kevinpapst** [comment]
But now we need some Unit Tests!

**Comment by simonschaufi** [comment]
I will take care of it

**Comment by kevinpapst** [comment]
Might be a little picky, but Kimai_Utility_StringUtility sounds strange.
Why not Kimai_Utility_String or Kimai_Utility_StringHelper?

And UnitTests - then fine to merge

**Comment by simonschaufi** [comment]
No compromise with the class name. The guys from TYPO3 already thought about a good name already ;)

**Comment by kevinpapst** [comment]
Is there a way to include it directly from Typo3 via composer? 
This seems to be a 1:1 copy of their code and we cannot simply copy&paste their code into our project.

**Comment by simonschaufi** [comment]
You can only include whole projects, not single files via composer.

That is what the GNU License says:

https://github.com/TYPO3/TYPO3.CMS/blob/master/LICENSE.txt#L85-L91

So the only thing that is missing is the mention of TYPO3

**Comment by kevinpapst** [comment]
Yeah, for some (sorry) stupid String functions... I am not convinced.

**Comment by simonschaufi** [comment]
Using glob makes more sense...

**Comment by kevinpapst** [comment]
Actually, if this is the only place we use this function: I totally support that!
What about updating that PR to use glob and remove the new class? And this is fine for merging...

**Pull request merged**
