### PR TITLE
Export to pdf2, standard / decimal time

### PR DESCRIPTION
**Pull request by claudegel**
This is to add the same functionality then in export to pdf by adding the possibility to export in standard or decimal time

### CODE REVIEW

**Comment by claudegel** [comment]
wait I've forget to add total standard time at the end of the list, still in decimal time. will update tomorrow. thank's

**Comment by claudegel** [comment]
Ok it is fine. my other PR on summary will also fix the small difference for the total standard time . So nothing to change

**Comment by kevinpapst** [comment]
Hey, you find a special interesting piece of Kimai code there ;-)
What does that pull request change?

**Comment by claudegel** [comment]
You have already merged a PR 'export to pdf' which allow user to export to pdf in standard or decimal time for the 'table' format. This one is for the same purpose but for the 'list' format. User can select to export in decimal or standard time. This way the export to pdf work in both time for the two format.

**Comment by simonschaufi** [comment]
@claudegel can you do us a favor and rebase that PR please to master branch?

**Comment by claudegel** [comment]
Ok I'll rebase it this week

**Comment by claudegel** [comment]
Hi I'm little bit mixedup since the many file structure change. 
Rebase to master mean make my changes against 
extentions/ki_export/_.php
or 
kimai/core/extentions/ki_export/_.php

**Comment by claudegel** [comment]
OK I've merged #544 and 543 in a new PR #704 It was easier them trying to rebase each one. So if it is ok you can remove this one

**Comment by kevinpapst** [comment]
Thanks, I am busy this weekend, but will check the new one next week!

**Pull request closed without merging**
