### PR TITLE
[BUGFIX] Fix broken mysql strict mode errors

### PR DESCRIPTION
**Pull request by simonschaufi**
Fixes: #709, #840

### CODE REVIEW

**Comment by kevinpapst** [comment]
I had a look at the user_edit function as well, but my changes look a little different:

```
    public function user_edit($userID, $data)
    {
        $data = $this->clean_data($data);
        $strings = array('name', 'mail', 'alias', 'password', 'apikey', 'passwordResetHash');
        $values = array();

        foreach ($strings as $key) {
            if (isset($data[$key])) {
                $values[$key] = MySQL::SQLValue($data[$key]);
            }
        }

        $numbers = array('trash', 'active', 'lastProject', 'lastActivity', 'lastRecord', 'globalRoleID');
        foreach ($numbers as $key) {
            if (isset($data[$key])) {
                $values[$key] = MySQL::SQLValue($data[$key], MySQL::SQLVALUE_NUMBER);
            }
        }

        $filter['userID'] = MySQL::SQLValue($userID, MySQL::SQLVALUE_NUMBER);
        $table = $this->getUserTable();

        if (!$this->conn->TransactionBegin()) {
            $this->logLastError('user_edit transaction begin');
            return false;
        }

        $query = MySQL::BuildSQLUpdate($table, $values, $filter);

        if (!$this->conn->Query($query)) {
            if (!$this->conn->TransactionRollback()) {
                $this->logLastError('user_edit rollback');
            }
            return false;
        }

        if (isset($data['rate'])) {
            if (is_numeric($data['rate'])) {
                $this->save_rate($userID, null, null, $data['rate']);
            } else {
                $this->remove_rate($userID, null, null);
            }
        }

        if (!$this->conn->TransactionEnd()) {
            $this->logLastError('user_edit transaction end');
            return false;
        }

        return true;
    }
```

**Review by kevinpapst — APPROVED** [review]

**Comment by simonschaufi** [comment]
you also changed something? Why is there no pull request?

**Comment by kevinpapst** [comment]
Just locally while testing ...

**Comment by kevinpapst** [comment]
I thought you would could include it in yours

**Comment by simonschaufi** [comment]
The missing line in your patch is:

```
$this->logLastError('user_edit failed');
```

all these transactions errors won't show you the real problem.

Please make a pr with your own improvements!

**Pull request merged**
