### PR TITLE
use $view->assign()

### PR DESCRIPTION
**Pull request by simonschaufi**
Changes proposed in this pull request:
- instead of assigning the variables directly into the view, use the api method
- remove $user assignment in checkuser as user variable is never used

### CODE REVIEW

**Comment by simonschaufi** [comment]
there is more to come...

**Comment by kevinpapst** [comment]
Why into master? Such big refactorings should go into develop

**Comment by simonschaufi** [comment]
because it doesn't break anything ;) that will be the last thing that goes into master. from now on i will commit into develop.

**Comment by kevinpapst** [comment]
I have multiple branches at home, that rework on several aspects, including the View. 
I already see hundreads of merge conflicts... I don't think its a necessary change for master and would highly prefer if you update the PR to point to develop.

**Comment by simonschaufi** [comment]
mhh, how can I know that you are working on the view as well? even if i point it to develop, that won't solve the issue of merge conflicts

**Comment by kevinpapst** [comment]
https://github.com/kimai/kimai/issues/601#issuecomment-196999116

But more importantly: does that fix anything beside your naging IDE comments about using "magic setters" ? ;-)
I would like to keep such huge refactorings out of the way for the next release.

**Comment by kevinpapst** [comment]
As discussed => merge into develop after fixing the missing empty lines in license header

**Pull request closed without merging**
