### PR TITLE
Invoicenumber

### PR DESCRIPTION
**Pull request by simonschaufi**
add configurable invoice number to bill and lots of code reformatting

### CODE REVIEW

**Comment by simonschaufi** [comment]
if you need some more documentation, i can explain what i have changed.

**Comment by ServiusHack** [comment]
I could swear I commented this yesterday, apparently I didn't ...

First, thank you for your effort here! I really appreciate it.

But I already merged #158, which now prevents automatically merging this due to a conflicting change in the updater script.

Second, I'd like to know the reason for your decision to only store the total value of the invoice in the database. It's not possible to regenerate the same invoice again (e.g. the date is missing) from this. I have #134 in mind here. If we implement some form of invoice tracking, we could just as well go the full way: Store a generated invoice for later retrieval in some folder, maybe with a database entry to reference it, store the date, the generating user, etc.

 Maybe you would like to extend your work on the invoice extension in that direction?

**Comment by simonschaufi** [comment]
you made a comment on the other pull request but not here ;)
you're welcome! i basically did it for myself to make my invoices a bit easier to generate.
1. i will fix my pull request again.
2. just for statistics (which is still missing), not for regenerate it as you can always do that by selecting the time and generate a new invoice (unfortunately not with the same invoice no right now). i don't know how professional software usually handles that. it's a first draft version - not finished yet. Let me brainstorm a bit how i could extend that to make it easily usable. Of course it would also be nice to talk with you personally about that if you want and have a bit time.

**Comment by kevinpapst** [comment]
Hi Simon! 

I understand your wish to reformat the code, but: Please don't sent so many changes in one pull request. You mixed up reformattings, whitespace changes, doc header, new functions and partially rewritten code ... 

We had major problems in the past with such pull requests and decided to reject them.
I know this might be frustrating and you are doing a lot for Kimai, but I will close this pull request (also it is not auto mergeable any longer). 

I'm fine with a reformatting pull request if it is ONLY whitespace changes and removed empty lines. I am fine with a new feature if it is only the new feature - but I personally can't review such a pull request.
Regarding the reformatting: we such discuss it in an issue. If we decide to fix the strange formattings (which I believe come from several OS and different IDE settings over the time), e should probably choose PSR2 and do that in one huge commit.

What is your opinion here? Could you sent in multiple pull requests (or at least the new feature in one single commit)?

**Comment by simonschaufi** [comment]
Hi Kevin, please dont close it, i will just attach a second patch to it that will be mergeable again. im not frustrated at all. it would just be better, if i would have direct access to the repo ;)

i will remove all the formating and only commit the real changes that matter for that commit but i need some time for it so just be patient, ok? i will also care about what you said before that i should do it properly with the other issue in mind.

**Comment by kevinpapst** [comment]
I don't like giving direct access to the repo. I think the best way is to always send pull requests, as it gives us (and everyone else) the chance to review and comment the incoming changes. That should increase the quality ... what is a minor problem in Kimai from time to time.
Using pull requests is the way I work as well, the only difference is that I can merge my own pull requests - which I normally only do when it was a minor change, otherwise I let Severin review/merge them. He is the last one to commit directly to the repo (which IMO is not best practice, but its up to him as he is the core developer). I would definitely prefer it most, if we never add our own changes to the official repo but let someone else do that. What do you think?

**Comment by kevinpapst** [comment]
BTW: We have a feature freeze, as we want to push out a new stable version and currently only merge bugfixes or minor improvements. So take your time for the patch ;-)

**Comment by kevinpapst** [comment]
We want to clear up all pull requests, so I am going to close this one. Its not mergeable.
If you still want to redo the patch, please do it in a new branch & pull request.

**Pull request closed without merging**
