### PR TITLE
SMTP Support for Kimai Auth Password Reset

### LINKED ISSUE #941: Forgot Password option isn't working
#### Expected behaviour
Password Reset Link should be sent to the registered mail-id.

#### Actual behaviour
Nothing is being sent to the registered mail-id.

#### Steps to reproduce
1. Open Kimai Home Page
2. Click on "Forgot my password" link
3. Enter registered Username >> Click "Reset Password" button

#### Reproducable on demo.kimai.org? [yes|no]
no,as i amn't a registered user on demo.kimai.org

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Kimai 1.1.0.1389 - Stable

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
[30.03.2017 15:36:23] password reset: kaniskan as user

### PR DESCRIPTION
**Pull request by timlegge**
FIXES #941 

Changes proposed in this pull request:
Add ability to use a SMTP server instead of sendmail for the sending of emails for Kimai authentication password resets.

requires the following to be added to includes/autoconf.conf:
```
$smtp_transport =  'smtp';
$smtp_name = 'Google';
$smtp_host = 'smtp.gmail.com';
$smtp_port = '465';
$smtp_auth = 'login';
$smtp_user = 'email@example.com';
$smtp_pass = 'emai_account_password';
$smtp_ssl = 'ssl';
```
STARTTLS is supported as well with:
```
$smtp_port = '587';
$smtp_ssl = 'tls';
```
Reason for this pull request:
Using existing smtp servers is usually easier than coniguring sendmail properly

### CODE REVIEW

**Comment by timlegge** [comment]
Will probably add drop downs to limit incorrect values during the install.  I also made an attempt at the German translation (thanks google - sorry Germany)

**Comment by simonschaufi** [comment]
What do you mean with your last message? I'm personally just overloaded with the amount of pull requests and issues and it's just a lot to handle. Sadly we are not a big dev team who always has plenty of time to check PRs.

I'm just not a fan of the whole thing with the parameters for the setup. It's really ugly code and needs to be refactored.

**Comment by simonschaufi** [comment]
See #778

**Comment by timlegge** [comment]
Hi

I have updated it for the recent changes on develop.  As for your comment:

> I'm just not a fan of the whole thing with the parameters for the setup. It's really ugly code and needs to be refactored.

Does that just meant the the installer code should be refactored in general or that you would like me to change something specific in this code?

Tim

**Comment by simonschaufi** [comment]
Leave it as it is right now as my refactoring of the autoconf file is not yet finished. Until then you can focus on other things. I will refactor it so that you can just assign an array with the changed settings and the remaining settings will stay as they are.

**Comment by timlegge** [comment]
Sounds great.  Thanks

**Comment by kevinpapst** [comment]
more than 4k changed files - there is something wrong in your PR

**Comment by timlegge** [comment]
Yeah, wondered about that.  I did a rebase and I think this pull request had been pushed to with other changes as well.  I will just pull out the differences for my commits and create a new branch and pull request...

**Pull request closed without merging**
