### PR TITLE
[FEATURE] add quicklinks for date selectors

### PR DESCRIPTION
**Pull request by peterwimmer**
New quicklinks to quickly select date intervals (today, yesterday, last week, last month, this week and this month). Added a new action bar in header for the quicklinks.

Changes proposed in this pull request:
- New quicklinks to quickly select date intervals (today, yesterday, last week, last month, this week and this month). Added a new action bar in header for the quicklinks.

Reason for this pull request:
- We often want to quickly switch different time intervals like "this/last week" or "this/last month". We added this feature in a new bar under the timer. It improves kimai for our employees a lot :) 

grafik

### CODE REVIEW

**Review by simonschaufi — APPROVED** [review]
looks good!

**Comment by simonschaufi** [comment]
thank you for your pull request!

**Comment by simonschaufi** [comment]
@peterwimmer i just noticed that the arrow bar at the bottom is not at the correct position (to increase the hight). can you confirm that?

On my test environment also the titles of the bottom list tables have are gone. In the Budget tab they are shown but not on the other ones.

**Comment by peterwimmer** [comment]
@simonschaufi yes i can confirm it, sorry for that! We are going through it today and adapt the positionings and make a patchx for it.

(We are using a two year old version of kimai at the moment in which some patches/features were added, but not in a way which could be given back to the repository. We try to split these changes out in separate branches now and rebase them to master. I missed the parts for the lower area there... :(. We will be more careful for other patch proposals....)

**Pull request merged**
