### PR TITLE
Adds a highly configurable LDAP-Authenticator

### PR DESCRIPTION
**Pull request by heiglandreas**
Then documentation for this Authenticator can be found in the
Authenticator documentation.

This PR replaces #407

### CODE REVIEW

**Comment by kevinpapst** [comment]
Any chance the LDAP_OPT_PROTOCOL_VERSION needs to be configurable?

**Comment by kevinpapst** [comment]
Oh any I would appreciate a new pull request with a version of this adapter, that will load a config file. 
From my perspective it is not very convenient, that a user has to create a new class and overwrite the base class properties in order to use your Adapter. 
Better create a config file with empty or some nice-default values that be used in combination with $authenticator = 'Ldapadvanced'; directly.

**Comment by heiglandreas** [comment]
Is there any special way that config files can be loaded in Kimai? I didn't find one therefore I used the same way the LDAP-Authenticator has been configured. A config file would be much more convenient!

I can include the protocol-version-option in there as well.

**Comment by kevinpapst** [comment]
Good question. I am not sure if we have a "default way" right now. Guess not ...

Maybe put it in https://github.com/kimai/kimai/tree/master/core/config as ldapadvanced.ini and use then use parse_ini() ?

**Comment by kevinpapst** [comment]
Must be merged aftewards: https://github.com/kimai/documentation/pull/1

**Pull request merged**
