### PR TITLE
BUGFIX #905

### LINKED ISSUE #905: GUI sync issues with Start/Stop button.
Expected behaviour:

Press start button. Row in table appears, starts recording and start button changes to stp button.

Actual behaviour:

Press start button. The button changes to stop then quickly back to start again, no new row doing recording. If I refresh the page everything is as it should be.

Note: Most times the button works correctly, its jut every now and again that is fails

Steps to reproduce:
It's obviously a timing issue. I'm using Firefox not sure if that has anything to do with the issue or not. 

Kimai version Stable 1.1.0

### PR DESCRIPTION
**Pull request by RStudios**
FIXES #905

Reason for this pull request:

Shouldn't reset the global 'offset' variable that calculates difference between server time and local time
Fixes issues described in #905
Awaits 'updateRecordStatus' before re-enabling buzzer @

### CODE REVIEW

**Comment by RStudios** [comment]
Third attempt to do it right, should be in correct branch now

**Comment by RStudios** [comment]
Added extra commit code:

Fixed calculation of the offset value to prevent negative timing
Disabled the buzzer while awaiting start/stop response from server
Corrected race condition and refresh of table when starting a new timer
Updated setTimeframe to take an optional callback parameter instead of the default 'hook_timeframe_changed'

**Comment by simonschaufi** [comment]
🎉

**Comment by simonschaufi** [comment]
@RStudios I noticed one more issue since I'm testing this since some weeks now. When you start the timer and then modify the currently running record (give it an earlier starting time), the timer on the right top doesn't update to the new time. Can you confirm that?

**Comment by RStudios** [comment]
@simonschaufi I'll look into it

**Comment by simonschaufi** [comment]
Another thing which was working before: Whenever you reaload the page, the couter starts from 0 again. This was working before as I was reading the start time from the server and then continued counting. This has to work so that I can finally merge it into master.

**Comment by kevinpapst** [comment]
what about reverting this PR and postpone its integration for the next release?

**Comment by simonschaufi** [comment]
@RStudios Today I made a new release but excluded this pull request from it as it is still not fixed completely. Could you please have a look into it so i can make a new release with this great bugfix included?

**Pull request merged**
