### PR TITLE
Use server time (resolves #507)

### LINKED ISSUE #507: Accurate time tracking
Please correct me if I'm wrong, but it seems that Kimai alternates between using the server's time and the client machine's time in order to calculate the duration of time tracked. If that is the case, it should be changed so that the start and end time are both drawn from the same source. Assuming that the server and the clients are perfectly synced can lead to errors if, for example, the start time is taken from the server and the end time is taken from the client.

### PR DESCRIPTION
**Pull request by HenryNe**
FIXES #507, #266, #403

Changes proposed in this pull request:
- Use server time in startRecord
- Adjust offset for ticktac (Buzzer)
- "offset" is timediff between server and local, only set ones on page load
- "startsec" is server time
- "now" is local time

Reason for this pull request:
- Fix different time base for start and stop timer

How to test:
1. Force a timediff between server and your local system. For example set your local time 1 hour in future of _same_ timezone. Set local time 14:00 CET, if the server time is 13:00 CET.
2. Press start and stop in same minute ( <60 sec)
3. Failed with old code recorded: In=14:00 Out=13:00 h'm=-1:00 rate=-1,00
4. After this patch recorded: In=13:00 Out=13:00 h'm=0:00 rate=0,0'

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hey @HenryNe - thanks again for contributing!
Please make sure that you have a clean commit history and learn how to keep your local git repo in sync with upstream. This should not be done by merging the remote, but by using a fast-forward or rebase.
Please do a squash commit, followed by a force push.

**Comment by HenryNe** [comment]
Git was very restive. Nothing of the squash was perfectly.
I checked out a fresh source from your develop and added my changes again.
Please use my new clean PR #681.

**Comment by kevinpapst** [comment]
It gets easier by the time^^

Did you see https://github.com/kimai/kimai/blob/master/.github/CONTRIBUTING.md#keep-your-fork-in-sync-with-original-repository
Its just as simple as that (and you can replace master in the example calls with develop as well).
If you squash an already pushed branch, you have to "force push" - otherwise git is complaining loudly ;-)

**Comment by simonschaufi** [comment]
if you use phpstorm, rebase is actually super easy. you can do it with a few clicks without entering any git command! do you use phpstorm?

**Comment by HenryNe** [comment]
Rebasing was not possible, because there was many other commits from me in my _develop_.
I have clean fetched from _upstream/develop_ now, and as long I do never commit something into my _develop_ I can merge and rebase without problems in future.

**Comment by simonschaufi** [comment]
don't rebase on YOUR origin/develop, rebase on upstream/develop! that should always work

**Comment by kevinpapst** [comment]
Or pull origin/develop into your develop (which you should not change anyway) and than rebase onto that

**Comment by HenryNe** [comment]
> Or pull origin/develop into your develop (which you should not change anyway) and than rebase onto 

This is what I'm doing now.

**Pull request closed without merging**
