### PR TITLE
Adds a highly configurable LDAP-Adapter

### PR DESCRIPTION
**Pull request by heiglandreas**
This PR replaces the currently available LDAP-Adapter with a highly configurable one. 

The new LDAP-Adapter can be used as authentication adapter for any LDAP-Server. Usage and Configuration are described in the acompanying LDAP_README.md file

Applying this LDAP-Adapter is a clear BC-Break as current configurations will not work any more. On the other hand, after an update the administrator has to reconfigure the LDAP-Adapter in any case as it has been replaced during the upgrade. Therefore that should not be an issue!

### CODE REVIEW

**Comment by scolytus** [comment]
1. nice :)
2. Why replace the existing one? I'd suggest to add an additional one, let's say `Kimai_Auth_Ldapnew` or `Kimai_Auth_Supeldap` - thus maintaining compatibility
3. I've PRs regarding certificate based authentication and better password handling in the queue. Are you interested in a rework of the authentication facilities? I'd have some ideas...

**Comment by heiglandreas** [comment]
## 

Andreas Heigl
Andreas@heigl.org

> Am 28.08.2014 um 17:10 schrieb Michael Gissing notifications@github.com:
> 
> nice :)

thanks ;)

> Why replace the existing one? I'd suggest to add an additional one, let's say Kimai_Auth_Ldapnew or Kimai_Auth_Supeldap - thus maintaining compatibility

I've already thought about that one after creating the PR. I'll rework that

> I've PRs regarding certificate based authentication and better password handling in the queue. Are you interested in a rework of the authentication facilities? I'd have some ideas...

Let's hear then! :) I'll see what I can do

**Comment by kevinpapst** [comment]
Hi and thanks for the Pull request! I really appreciate your contribution.

Instead of merging, I would ask you to create a new pull request:
- Create a new Branch
- Create your Ldapadvanced class in there
- Send in the new Pull request and close this one

The current Pull request rewrites the history of the default LDAP class, which shouldn't be merged into master.

About the LDAP_README.md. Do not add the infos there but in our documentation:
https://github.com/kimai/documentation

Exactly this file:
https://github.com/kimai/documentation/blob/master/administrator/authenticator.md

**Comment by heiglandreas** [comment]
Closed in favour of #413

**Pull request closed without merging**
