### PR TITLE
Fix issue #1302

### LINKED ISSUE #1302: Rounding Issue since v1.3.3
Since v1.3.3 there is an issue with the rounding-function. If i add an entry manually like this
kimai_rounding_before

it will actually be stored like that
kimai_rounding_after

If the end time had been 20:29:59, it would have been rounded correctly, like expected.
I expect, that times should be forced to be rounded to a full 15 minutes, no matter if the entry is added manually or "recorded".

If have activated these 2 options:
kimai_rounding_option_1
kimai_rounding_option_2

### PR DESCRIPTION
**Pull request by simonschaufi**
FIXES #1302 

Changes proposed in this pull request:
- Fix rounding issue introduced in release 1.3.3

The same rounding rules are used as kimai v2 now. Thank you @kevinpapst!

### CODE REVIEW

**Comment by hh-it-co** [comment]
Thanks for your investigation. I've tested your fix, but it does not work as expected. Now, it seems like the rules for rounding will completely be ignored, except for recorded entries. The rounding is not forced as before during manual processing. Entries with less than the rounding-time will be rounded down, no matter if rounding down is allowed or not.

**Comment by simonschaufi** [comment]
Do you mean the new release? I've tested it really well and it works how I would expect it.

If rounding down is allowed, it rounds either up or down. If it is not allowed, it always rounds up.

**Comment by hh-it-co** [comment]
I will test again with 1.3.4

**Comment by simonschaufi** [comment]
if you need the release zip file, I can provide that.

**Comment by hh-it-co** [comment]
No, thanks. I test it directly from the repo.

**Comment by hh-it-co** [comment]
It is still the same: If i start recording and stop it immediately after that, i expect it to round up to 15min. But it rounds down to 0min, no matter if i enabled rounding down or not.

**Comment by hh-it-co** [comment]
Maybe i should go one step back:
My goal is to settle every quarter of an hour started. I expect to achieve this by activating the two options maintained in the error-descrioption.
Maybe I am wrong with this expectation?

**Comment by simonschaufi** [comment]
Yes, the "fixed" situation is that the rounding will only take affect if at least 15 min are over since both values will be rounded up to the next 15min and will be the same.

From your expectation the expected result should be like this:

`1:05 - 1:06 -> 1:15 - 1:30`

Right?

If you expect the following, then you should activate the round down:

`1:05 - 1:06 -> 1:00 - 1:15`

but well, even that would currently only result in the values to be the same since `1:06` will still be rounded down. The other thing that I could do is to always round the start down and the end up. Then you would get the expected result (`1:05 - 1:06 -> 1:00 - 1:15`) I guess.

**Comment by hh-it-co** [comment]
No, i would expect it to be

1:05 - 1:06 -> 1:00 - 1:15

**Comment by hh-it-co** [comment]
In v1.3.3 the behavior was exactly as i expected. The only error thing was that the hole time-block was moved a quarter hour further after manually editing.
What i get in v1.3.4 is this (the displaying-errors are problems from the capturing software):

kimai_rounding_1 3 4

**Comment by hh-it-co** [comment]
This is, what v1.3.3 does (same settings without rounding down). Thats, what i would call the right behavior:

kimai_rounding_1 3 3

**Comment by simonschaufi** [comment]
@hh-it-co Expected behavior `1:05 - 1:06 -> 1:00 - 1:15` now implemented. Please update to release 1.3.5 and allow round down.

**Comment by hh-it-co** [comment]
Works like a charm. Thank you very much!

**Comment by simonschaufi** [comment]
You are welcome. If you want to support my work, you can do so at https://paypal.me/simonschaufi

**Pull request merged**
