### PR TITLE
Fixes #509

### LINKED ISSUE #509: advance setting changes overwrite
To use LDAP I added to the includes/autoconf.php
$authenticator = "ldap";

When you go into the software and make changes to the advance settings the file gets overwritten and the ldap entry removed, breaking ldap logins.

### PR DESCRIPTION
**Pull request by kevinpapst**
added new Kimai_Config class
using psr-0 instead of classmapping in composer autoloading
reading default values from Kimai_Config instead of writing them multiple times within the code

### CODE REVIEW

**Comment by simonschaufi** [comment]
please no code formatings together with code changes

**Comment by kevinpapst** [comment]
LOL^^ Team members can!

**Comment by simonschaufi** [comment]
yes but then just make one pr with code formatings and one with code changes

**Comment by kevinpapst** [comment]
Great commit history after merging ;-) 
Closing this one and sending in a new one, once the rest is merged.

**Pull request closed without merging**
