### PR TITLE
change gmdate for a public function timelenght

### PR DESCRIPTION
**Pull request by claudegel**
Sorry but I was using gmdate to calculate the duration in hh:mm but gmdate cannot go over 24h so I change it for a new function timelenght which work ok for any duration lenght

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hey, just saw your pull request today. 
Why sorry? Did you contribute to the file before? Is there a bug?
What do I have to do to reproduce your problem?

**Comment by claudegel** [comment]
This is part of the export to pdf2 PR. I was using gmdate() to calculate the time duration but that function could not go over 24hr so I've changed to a specific function to be able to calculate time duration. This allow to correct time duration calculation in standard time in export to pdf2

**Comment by simonschaufi** [comment]
@claudegel since we moved the whole file structure one folder up, could you please rebase your PR to master branch?

**Comment by claudegel** [comment]
Ok I'll rebase it this week.

**Comment by simonschaufi** [comment]
@claudegel ping

**Comment by claudegel** [comment]
Still there but very buzzy. Not familiar with rebase. hope to send commits soon

**Comment by simonschaufi** [comment]
do you use phpstorm? there it is super easy.

**Comment by claudegel** [comment]
I'm using ZendStudio, I'll have a look to phpstorm. Thank you
Sould I do it against development or master

**Comment by simonschaufi** [comment]
@claudegel we have free phpstorm licenses to give away for people who want to be part of our team and want to continue improving kimai.

I think the best is against develop and then close this PR and open another one against develop.

**Comment by kevinpapst** [comment]
Hey @simonschaufi , can we chat about that please.

**Comment by claudegel** [comment]
OK I've merged #544 and 543 in a new PR #704 It was easier them trying to rebase each one. So if it is ok you can remove this one

**Comment by kevinpapst** [comment]
Closing this on in favor of #704

**Pull request closed without merging**
