### PR TITLE
Many corrections

### PR DESCRIPTION
**Pull request by claude-ws01**
ok, I finally succeeded...
...as requested my corrections in a pull request.

Claude.

### CODE REVIEW

**Comment by simonschaufi** [comment]
Could you please describe in details what the corrections are (explaining WHY this needs to be changed) as i don't want to break code and even better: make single PRs for every single change and not bunch them together as it is hard to do a research afterwards if something goes wrong

**Comment by claude-ws01** [comment]
wow?

Are you aware that this ticket was opened on Jun 30 2015?
Are you aware that I went on with my own branch: https://github.com/claude-ws01/Kimai-i ?
Are you aware that by mid-August 2015 I was done with my code revision ?

I you had done a quick investigation, you would have found most the information in issues #496, #497, #498, #501 and #502. AND you would remember that I went my own way (and why).

But if you're really interested in improving Kimai, you can look at the updates I've done from June 26 and August 26 2015, and gave birth to Kimai-i (https://github.com/claude-ws01/Kimai-i). Here's a summary:

```
=== v0.10.1-b6 ======= 2015-08-xx ============ db revision 2000 ========================================================
- bugfix: ki_export: processor.php: array not initialized.
- export-print: some corrections
- logger: added more validation.
- gitignore: some corrections, some needed files were excluded.

=== v0.10.1-b5 ======= 2015-08-10 ============ db revision 2000 ========================================================
- corrections in https mode.


=== v0.10.1-b4 ======= 2015-08-10 ============ db revision 2000 ========================================================
- admin panel: revision of all panel into a single function.php files. No reason to duplicate code in init.php and
    processor.php
- for developpers: added the permission field name in title for global/membership role panels. Hover over the checkbox
    to see what permission field name.
- corrections: typos here and there.
- installer: db schema is now in kimaii.sql (excluding permissions).
- https: centralized evaluation. Testing.
- password minimum lenght: now configurable in /include/vars.php. Set it as you see fit. Messages and evaluation
    modified as well.
- installation: default host was 'localhost' now is '127.0.0.1'. Privilege more direct and fast access. No DNS lookup.
- bugfix: timer display on Firefox.
- bugfix: 'other_groups' privileges not applied in project add-edit. Was limited to user's group only.
- mysql classes revision: regrouped all functions related to roles evaluation in a third file/class called roles.php.
    Less searching all over (in func, kimai...). And some cleaning up.
- time range initialisation correction: If client's timezone is different and ahead of time from preference's timezone,
    new recording may not display because of timezone's time is next day. Now, timeframe's "to_date" is set to 'today+1'.



=== v0.10.1-b3 ======= 2015-08-07 ============ db revision 2000 ========================================================
- language: Google & manual traduction in Spanish. Inclusion of incomplete traduction in German.
- Doc: some more small documentation in, now, /doc folder.
- grfx: clean up of unused images.  Regrouping of images that are not refered in the skin, to the main /grfx folder.



=== v0.10.1-b2 ======= 2015-08-06 ============ db revision 2000 ========================================================
- bugfix: time of day difference between client & server: Messes up with the time recording. Server was behind and
    timer would start at -50 second because of a 10 second difference. I removed this attempt of managing the offset
    between client & server, because in fact it is irrelevant. What is, is to have precise delta between start and
    stop. Since it is now ONLY the server's that is used, for both start/end. So even if client is 5 minutes behind,
    the user may see a difference in the hour:minutes, it will show in the start as well as the end, but the gap is
    valid.
- some corrections in query results evaluations.



=== v0.10.1-b1 ======= 2015-08-06 ============ db revision 2000 ========================================================
- bugfix: invoice panel width not following. Solved.
- demo: some attempt to figure out how ki_demo (demoextention) is supposed to perform, or if it even ever worked.(!)
- DEMO_MODE: introduction of DEMO_MODE to enable/disable some feature.
    Nothing to do with ki_demo(demoextension).
- centralized cookie creation
- language: now selectable on login page. Can also be set in the uri (?language=en), practical when having different
    language customers, and need to send them a link.
- revision of language selection process when initializing. Inclusion of cookie ki_language. Priority: uri, cookie,
    pref, default and english if none is available.  Also, language decision is centralized in transaction.class,
    nowhere else. Simplicity please!



=== v0.10.0-b5 ======= 2015-08-04 ============ db revision 2000 ========================================================
- start and stop recording time are now both taken from the server.  And it will show in local time as define in the
    user's preferences.
- minor corrections
- correction in delete_user




=== v0.10.0-b4 ======= 2015-07-27 ============ db revision 2000 ========================================================
- strengthen even more the choosing of update/install process with cleaner/safer redirection.

- revised internal version check. Now, if no db revision, then only update core.version number. No need to run updater.



=== v0.10.0-b3 ======= 2015-07-27 ============ db revision 2000 ========================================================
- grrr. having some difficulties with git...



=== v0.10.0-b2 ======= 2015-07-27 ============ db revision 2000 ========================================================
- languages: some modifications in EN and FR.
- bugfix: iconv_set_encoding deprecated WARNINGS with PHP v5.6: Made new function ki_iconv_set_encoding to replace
    iconv_set_encoding. Function checks PHP version. This affects only zend framework 1.
- bugfix: java validation of time in timesheet edit. We do not care about seconds!!



=== v0.10.0-b1 ======= 2015-07-25  ============ db revision 2000 =======================================================
Notes: This jump to v0.10.0 db revision 2000, is my major overhaul of original Kimia v0.9.3rc1. There is still work to
do, but from what I have revised, the core is functionnal.  Here a short and incomplete list of what I have done.

- improvement: removed all references to 'server_conn', and 'pdo', as there are NO pdo processing in Kimai.
- improvement: removed 'server_type', unused.
- improvement: removed abstract mysql class, simply unnecessary with no real gain.
- improvement: added all default preferences for new users in global config.
- improvement: removed one unnecessary database locks ( no need when not multi table updates, even less when only select)
- improvement: upgraded the db transaction handling method
- feature: preferences is now unified, for customer or user. Methods, Variables & db. User/Customer's prefs are both in
    the preference table.
- improvement: user_id & customer_id are now both checked for uniqness against preference table.
- features: customer can now set their own preferences.
- improvement: massive revision of global variables (some people should learn about why and how to use
    global/protected/private variables/method, and abstract)
    ~ GLOBALS: kga, database, view (zend framework), translation.
    ~ important $kga arrays:
        * any       (id, type, common to user & customer)
        * conf      (copy of configuration table)
        * customer  (when logged-in, customer's data)
        * lang      (locale translation)
        * pref      (preferences of both user/customer)
        * status    (copy of status table)
        * user      (when logged-in, user's data)
- improvement: handling of grid header in timesheet,expenses,export...
- improvement: PSR standardizing of all namings of tables and rows (excluding role related)
- improvement: PSR standardizing of "role" related row names in db-tables. no more "-", instead "_".
- improvement: status table now loaded in translation array, what ever translation exist will
    override status name from db... Simply put, change language and status names
    will follow. If no translation exist (because it's new status) then the status
    name from the db will be shown.
- improvement: debug panel: deactivate log updates while panel not active (avoid useless http requests)
- feature: extention's css & grfx folders can now be included in a skin folder, then modified to change the appearance
    and it will override the extensions default.
- bugfix: bottom filters not always displaying when navigating from one tab to another.
- feature: new *root* privilege gives access to everything, no matter if user has privileges or
    not. Glogal role "edit admin panel advanced settings" is *root*.
- improvement: page generators for timesheet, expense & export are now shorter by half, code efficient
    and easier to read.
- improvement: lots more popup 'tips' on most action links (icons, headers...), improving understanding of
    what things do.
- bugfix: multiple table update without transaction (in project)... added.
- bugfix: transaction now support multiple level. A method starts a db-transaction and calls another method that also
    starts a db-transaction while already inside the previous transaction. Now ok.
- improvement: force closing database at end of php process, giving a chance to check if there were incompleted
    db-transaction (ie. commit was not called, or some issue prevented the end of the transaction) and log a
    correponding warning.
- improvement: floating windows now always centered.
- improvement: added money symbol besides money field labels, clarifying what's suppose to go in there.
- improvement: added "processing" visual feedback, to let know the user his request is being processed. Not very
    noticable on fast server, but on slower local server.
- improvement: corrected some ambiguous German traductions (tracking_number -> order/ref code, effort -> (still
    figuring out this one)(I guess it is close to expenditure, costs, additional expenses...)
- change: minimum width down from 970px to 900px.
- optimization: removed many db-get-user-groups of current user, as groups is already loaded in $kga.
- improvement: top page displays better and resize flows better
- bugfix: added missing message var initialization for adding user, project, customers... in admin.
- improvement: on page load, now shows the user as filtered. Before you would be wondering why all the timesheets were
    not shown.
- optimization: - reduction of the number of http request from 100~110 to 50~60.
                - reduction of transfers from 428KB to 277KB (on the first fetch)
                - reduction of transfers on subsequent fetch as well, by a minimal 10KB

=== v0.9.3-rc1 ======= 2015-07-01  ============ db revision 1394 =======================================================
Branch from Kimai v0.9.3-rc1, db revision 1394
```

Happy new year!

**Comment by kevinpapst** [comment]
WOW, Claude ... you are THE man :+1: 
Instead of creating your own fork, you could have waited and contributed to the original project, but hey ... enjoy coding for yourself only. Thats the spirit of open source.

**Comment by claude-ws01** [comment]
hey!! Isn't that "Pope to the rescue" [again] rescuing it's young lost [again] protegée...

How nice of you to drop in... with nothing of profound importance to say [again].

6 months have past and the ticket I wrote are still pending...  Hell, it took 2 years to go from 0.9.3 beta to release... 2 YEARS.

And I'm suppose to wait for you guys to wake up... hell, you're still have not figured out head from tail; still debating about the color of the tiles in the bathroom... too afraid of taking calculated risks... [right...  you need to know how to calculate before hand]...

And you think you can give lessons about open source spirit... that is a good one...

One big difference between you and me, I don't blame you for going at your own [slower] speed. I took on myself to do what I needed to do, when I needed to.

What I find really annoying is people behaving like stagnant and clueless CEO's, telling people what to do so they can feel important.

The other thing I find quite annoying is people covering up their mistakes.... people that pretend not loosing head by blaming others.

Oh, and why are you answering on this issue?  Simon is not able to answer for his own cluelessness?

You know what's worse than one incompetent... two incompetents covering for each other.

Get a life!

**Pull request closed without merging**
