### PR TITLE
New theme: Zadia

### PR DESCRIPTION
**Pull request by zetxek**
I've created a new theme based on the official one, with the aim of making the interface simpler, cleaner and more user friendly.

It has a new color scheme, some new icons (brand new and based on copyleft ones, credited on the theme), and some visual adjustments. As the HTML structure is the same it does not have many changes in that sense, but the GUI has been flattened to accomplish a simpler and easier to the eye look.

image

In the image attached you can check the theme, although the committed and pushed theme uses the default kimai logo, not zadia's one.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Hi zetxek, the screenshot looks great! Thanks a lot for sharing :)
I will try to have a look this weekend, then merge it and come back here.

**Comment by zetxek** [comment]
@kevinpapst great you like it! My plan is continue on theming the inside pages, like reporting, invoices, and so on, but coming from this base in colors and aesthetics. Also, fixing some little problems with assets

**Comment by zetxek** [comment]
Hey, do you need some changes to merge this theme? Probably they could be made!

**Comment by kevinpapst** [comment]
Nope, sorry for the missing feedback. We have a codefreeze, thats why I am not merging. 
I'd love to merge your theme as soon as this is over! Please hang on, I'l let you know :)

**Comment by simonschaufi** [comment]
I will change the margin for the tabs because they are overlapping.

**Pull request merged**
