### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by vinzenzweber**
Fixing a simple bug in the API which makes calls to get_timesheet without the user ID.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Please do create a branch for your pull request in the future. 
And please do not commit merges, these changes are already in our master branch.

**Comment by vinzenzweber** [comment]
I am not so used to pull requests yet, sorry for the inconvenience, I will setup my branches properly for future pull requests. ;)

**Comment by kevinpapst** [comment]
We are still learning Git as well ... branches seems to be the best way for us to review and merge your changes :)

**Comment by vinzenzweber** [comment]
:+1:  Yes, that's what it says here as well: https://help.github.com/articles/using-pull-requests

**Pull request merged**
