### PR TITLE
Updater cleanup

### PR DESCRIPTION
**Pull request by kevinpapst**
This pull request refactores the updater.php:
- create a new updater/ directory containing all related files
- moved db_restore.php there
- moved images from grfx/ to updater/ and deleted grfx/
- created header/footer and reusable error templates, to separate HTML from PHP
- removed updates before Kimai 0.8 as they were broken and needed PDO support. Added an error message and download link to older Kimai version which has update support for these very old versions.

### CODE REVIEW

**Comment by simonschaufi** [comment]
please rebase and commit again. too many code (formatting) changes

**Comment by kevinpapst** [comment]
Hey, unfair! My branch was mergeable when I openend up that Pull request.
You should not come, speed up and merge your PR before and let me run into conflicts - especially when your changes are done by a tool that can do its work again!

**Comment by simonschaufi** [comment]
I'm sorry, I saw your changes AFTER I already merged it.

**Comment by kevinpapst** [comment]
New PR #574 with clean commit history, therefor closing this one

**Pull request closed without merging**
