### PR TITLE
iso date format

### PR DESCRIPTION
**Pull request by thedayse**
FIXES #
- Remove the hardcoded dd.mm.yyyy date format for the timesheet date input and instead use the
jquery ui datepicker $.datepicker.parseDate( format, value, options ) function to parse dates using the users preferred format (entered in the admin panel). #139
- Added a few swedish translations for today, yesterday etc ( and table_time_format #1135, didn't look at other languages).
- Added a language tag to the opening html tag.

Improvements ..
- Replace the newsticker animation with a css based animation.
- If the end date/time for a timesheet entry is empty a duration in minutes may be entered and the end time will be calculated from that duration. 
- Added links to the timesheet input form similar to the "now" link. These links when clicked change the start time so that it equals the previous finish time. The other link changes the end to the next start time.  This simplifies timesheet gap removal.. (#995 )
- Added summaries to the timesheet. Totals for each day, week, and month H:m.s 
- Removed some styles that were not required from table cells
- Quick links for this year and previous year

Broken .. the phpunit tests .. I have no idea. I tried updating phpunit to the latest version in the composer reqs and travis.yml. But then all the unit tests need updating as well.

### CODE REVIEW

**Comment by thedayse** [comment]
Is there any chance this will get merged? I do understand if it doesn't get in -  the input date format isn't a big deal for existing installations and I've changed quite a few files.

**Comment by simonschaufi** [comment]
Sorry, reviewing pull request takes quite some time as we don't want to merge things which aren't properly reviewed and tested.

**Comment by Lagneaux** [comment]
Hello Simon,

As you know, we have a problem with editing invoices:
Missing time period

I confess I do not understand, in this post, what to do.
Could you upload the files that are to be modified and overwritten in the script? What is the tree for each of them?

A big thank you in advance!
Regards,

**Review by sollermun — APPROVED** [review]
Worked out beautifully!! These changes really should be incorporated as a default. People in the United States never use day/month/year format. ISO is an acceptable middle ground.

**Comment by sollermun** [comment]
I am having the same issue as Lagneaux. Creating invoices after applying these changes results in an error "Missing time period." Any fix for that?

**Comment by sollermun** [comment]
One issue that I've noticed is that the date picker for expenses does not work with this modification. It still wants to go with a hardcoded dd.mm.yyyy format.

**Comment by simonschaufi** [comment]
It would be great if you could add separate pull requests for every single feature. I see you also commit lots of stuff totally unrelated like updating phpunit.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).

**Pull request closed without merging**
