### PR TITLE
Fix remote api

### PR DESCRIPTION
**Pull request by kevinpapst**
FIXES https://github.com/kimai/kimai-mobile/issues/15

Changes proposed in this pull request:
- do not return hidden entities via JSON/SOAP

### CODE REVIEW

**Comment by simonschaufi** [comment]
Either provide a unit test or a way to test this manually

**Comment by kevinpapst** [comment]
You could use the kimai-mobile version and check beforee and after. Projects and such should not include hidden entries any longer

**Comment by simonschaufi** [comment]
I'm just trying to write some unit tests but the API class is not so easily testable.

**Comment by kevinpapst** [comment]
Uh, nice! I know, like all the old classes ... thats why I skipped it ^^

**Pull request merged**
