### PR TITLE
Fixing remote expenses queries (#1054)

### LINKED ISSUE #1054: Listing expenses are not working over remote API
#### Expected behaviour
List of expenses should be fetched over JSON API.

#### Actual behaviour
GetExpenses does not work correctly when called over the JSON API. The query is invalid.

#### Steps to reproduce
Call getExpenses over JSON API interface.

#### Reproducable on demo.kimai.org? [yes|no]
yes

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
All versions so far

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
None

### PR DESCRIPTION
**Pull request by Viras-**
FIXES #1054 

Changes proposed in this pull request:
- Fixing queries (wrong USING join)

Reason for this pull request:
- Invalid queries

### CODE REVIEW

**Review by simonschaufi — APPROVED** [review]

**Comment by simonschaufi** [comment]
Thank you!

**Comment by Viras-** [comment]
You are welcome. Are there any plans for a new release yet?

**Comment by simonschaufi** [comment]
Well, I would love to but there is one thing in dev branch which is a blocker so far. If you could have a look at it, it would be great.

https://github.com/kimai/kimai/pull/1047#issuecomment-348915358

When that is fixed, I will do a new release.

**Comment by Viras-** [comment]
There you go - see #1182

AFAIK this only can be done like I implemented it now - a time sync can never be done on client side only.

**Pull request merged**
