### PR TITLE
adding a quick note button in the timesheet tab

### PR DESCRIPTION
**Pull request by claudegel**
I've added a new button in the timesheet tab to let people add note during the time is running or after. I've made that button on/off with a checkbox in the preference where I've added a new tab for timesheet preference. I will use that tab to add preset default location that can be overwrited when editing the note.

### CODE REVIEW

**Comment by claudegel** [comment]
I've also added default location for timesheetentry in preferences and possibility to link tracking number to the timeEntryID with checkbox in preference.

**Comment by kevinpapst** [comment]
Hi, sorry but I can not accept/merge your pull request. What happened here is the "normal" mistake beginners make (I did also). First: You did not use a branch. Second: You merged our master into your changes - this will completely kill our history and is not possible to review.

There are fantastic documentations on how to work with Git and Branches here at GitHub, for example: https://help.github.com/categories/63/articles
For the first steps this is nice too: http://try.github.io/ 

I am sorry because we'd like to incorporate your changes and don't want to frustrate you. But you changed more than 1500 files (on accident) and it is impossible to see what exactly happened.

**Comment by claudegel** [comment]
Thanks i'll redo it from a branch so you can see the changes. Is it possible to wipe my claudegel/kimai to remove all my changes and start again from scratch ? I still have the modified version at home. I gona do my RTFM

Thanks again

Claude Gelinas agr.
Phyto Ressources Inc.

**Comment by kevinpapst** [comment]
Sure, open your kimai repo and go to Setting > "Delete this repository" and fork it again.
Then create a branch and add all your changes there. This one should be used for the pull request.

I like this tutorial to keep your master up-todate: http://blog.evan.pro/keeping-a-clean-github-fork-part-1

**Comment by claudegel** [comment]
Le Sun, 12 May 2013 05:21:42 -0700,
Kevin Papst notifications@github.com a écrit :

> Sure, open your kimai repo and go to Setting > "Delete this
> repository" and fork it again. Then create a branch and add all your
> changes there. This one should be used for the pull request.
> 
> I like this tutorial to keep your master up-todate:
> http://blog.evan.pro/keeping-a-clean-github-fork-part-1
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kimai/kimai/pull/171#issuecomment-17777086

Ok I've deleted the claudegel/kimai and fork a new one
then created a branch called quick-note

on my local machine I've done the following
mkdir kimai-devel
cd kimai-devel
git init
git remote add origin https://github.com/claudegel/kimai.git
git remote add upstream https://github.com/kimai/kimai.git
git clone https://github.com/claudegel/kimai.git
git fetch upstream
git merge --ff-only upstream/master
git push origin master
git checkout -b devel/quick-note

now under kimai-devel I have the following dir 
build  core  docu  kimai  README.md  test

and in the kimai dir I have the same
build  core  docu  README.md  test

so on which file do I do my changes ?

in kimai-devel or in kimai-devel/kimai

I just don't want to start wrong again

## Thanks,

Claude Gélinas agr.
Phyto Ressources Inc

**Comment by kevinpapst** [comment]
Thats not the right way to do it.
First fork kimai here on Github, then clone your GitHub repository on your machine.
After that create a branch and work on it. Commit and push that branch, what will create a new remote branch (there are local and remote branches possible). Use that new remote branch here on GitHub to sent the Pull Request.

The "keeping a clean github fork" is not important here, it was more a FYI to keep your cloned master up-to-date with the latest changes in our kiami repository.

Don't get confused with all that. Start with forking, cloning, branch, commit & push. The rest will come when you need it ;)

**Pull request closed without merging**
