### PR TITLE
How to build the release zip

### PR DESCRIPTION
**Pull request by uli-heller**
Reason for this pull request:
- I wanted to use version 1.3.5, but didn't find a kimai_1.3.5.zip. So I described how to create it.

### CODE REVIEW

**Review by simonschaufi — CHANGES_REQUESTED** [review]
The changes in build.xml are valid but the kimai repo shouldn't be used for documentation. That should be done on the www.kimai.org repo and somewhere you will also find it in the v1 folder

**Comment by uli-heller** [comment]
OK, I understand this, I'll modify the pull request. But why is there a file named INSTALL.md? It doesn't work unless you have a zip file as described in RELEASE.md (... which is going do disappear).

**Comment by uli-heller** [comment]
Please note:  The description INSTALL.md is already included in www.kimai.org, file _v1/team.md

**Comment by simonschaufi** [comment]
You don't necessarily need the zip file. The git repo and composer install will almost do the same. The zip file is just a bit smaller as i exclude some folders

**Comment by uli-heller** [comment]
Am 2019-11-09 03:14, schrieb Simon Schaufelberger:

> You don't necessarily need the zip file. The git repo and composer 
> install will almost do the same.

Thx, but this means: additional dependencies for the installation. My 
kimai server doesn't have composer installed at the moment, for 
example...

**Pull request closed without merging**
